export const ageRanges = {
  CHILD_AGE_MIN: 0,
  CHILD_AGE_MAX: 12,
  TEEN_AGE_MIN: 13,
  TEEN_AGE_MAX: 19,
  ADULT_AGE_MIN: 18,
  ADULT_AGE_MAX: 65,
  SENIOR_AGE_MIN: 65,
  SENIOR_AGE_MAX: 100,
  AGE_MIN: 0,
  AGE_MAX: 100,
}
